env:
  discordToken: "OTA0NDcwNDUzMjc4NjE3NjAw.GgDcRZ.XlpogCVhHB5TNh5wUmdryQ27ABIyWiZ4_20EyA"
  nftMarketplaceAddress: "0xb4fa69997f7560fe48f375b03f73b8774cb3bf5a"
  testnet: true
  zildexr:
    key: "cd66db4a-cfc8-4db3-951c-b9c633566196"
