env:
  discordToken: "OTA0NDcwNDUzMjc4NjE3NjAw.GgDcRZ.XlpogCVhHB5TNh5wUmdryQ27ABIyWiZ4_20EyA"
  nftMarketplaceAddress: "0x552f96a968cac7a910fdeb668181b0f6e50e4fae"
  testnet: true
  zildexr:
    key: "cd66db4a-cfc8-4db3-951c-b9c633566196"
