apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.app.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.app.url }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          env:
            - name: discord_token
              value: {{ .Values.env.discordToken | quote }}
            - name: nft_marketplace_address
              value: {{ .Values.env.nftMarketplaceAddress | quote }}
            - name: is_testnet
              value: {{ .Values.env.testnet | quote }}
            - name: indexer_key
              value: {{ .Values.env.zildexr.key | quote }}
            - name: recently_listed_channel
              value: {{ .Values.env.discordChannels.listed | quote }}
            - name: recently_sold_channel
              value: {{ .Values.env.discordChannels.sold | quote }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
          volumeMounts:
            - name: configmap
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: configmap
          configMap:
            name: {{ .Release.Name }}-configmap
