image:
  app:
    url: 981130112916.dkr.ecr.us-east-1.amazonaws.com/zilkroad/discord-sales
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: aws-registry
  filebeat:
    url: elastic/filebeat:7.17.0
    pullPolicy: IfNotPresent

namespace: devnet

logPath: /app/logs

replicas: 1

env:
  discordToken: ~
  nftMarketplaceAddress: ~
  testnet: ~
  zildexr:
    key: ~

resources:
  limits:
    cpu: 0.1
    memory: 256M
  requests:
    cpu: 0.1
    memory: 256M
