name: Lint and Build Zilkroad Discord bot

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'zilkroad_discord_bot/**'

  # Allows manual trigger
  workflow_dispatch:

env:
  CONTAINER_NAME: zilkroad_discord_bot
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: zilkroad_discord_bot/Dockerfile
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: ./zilkroad_discord_bot
      id: build-image
      run: |
        docker build -t $CONTAINER_NAME:$IMAGE_TAG .
